[workspace]
members = ["waterfall-core", "waterfall-infra"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
walkdir = "2.5"
tempfile = "3.13"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "gif", "webp", "bmp", "tiff"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
